<?php 
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$media = $this->getImageMediaPath();
?>
<style>
	.brand-char {
    min-width: 300px;
    float: left;
    min-height: 130px;
}
</style>
<div class="featured-brands">
	<div class="title-brands">
		<span>Manufacturers</span>
	</div>
	<div class="container" id="box-brand">
		<div class="row">
			<?php foreach($featured as $_fbrand):?>
						<div class="col-md-2">
							<span>
									<?php if($_fbrand->getUrlKey()):?>
										<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
									<?php else:?>
										<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
									<?php endif;?>
									<?php if($_fbrand->getLogo()):?>
										<img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>" style="height:100px"/>
									<?php else:?>
									<span class="brand-title">
										<?php echo $_fbrand->getName();?>
									</span>
									<?php endif;?>
								</a>
							</span>
						</div>
			<?php endforeach;?>
		</div>
	</div>
</div>


