<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);    

$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
// Get Menu
$menu = $objectManager->get('\Magento\Theme\Block\Html\Topmenu');
$_menu = $menu->getHtml('level-top', 'submenu');
// Get Current Category name
     
?>
 <?php
    $categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
    $topCategory = $categoryFactory->create()
    ->addAttributeToFilter('url_key','hot-deal')
    ->addAttributeToSelect('*')
    ->getFirstItem();
    $topCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
    $saleCate = $topCollection->create()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($topCategory)
    ->addAttributeToFilter('visibility', ["neq" => "1"])
     // ->setPageSize(6)
    ->setOrder('created_at', 'DESC')->load();
    ?>
<div id="box-filter-m">
    <div class="category-current">
        
    </div>
    <div class="count-p">
      <?= count($saleCate); ?>  Item
    </div>
    <div id="filter-p">
        <span>Filter</span>
    </div>
</div>
<div class="sidebar sidebar-main">
    <div class="block filter categorySidebar" id="layered-filter-block">
        <h4 class="title-sidaber title-">CATEGORIES</h4>
        <div id='cssmenu-left'>
            <ul>
            <?= $_menu ?>
            </ul>
        </div>
    </div>
</div>


<div class="products wrapper grid products-grid" id="content-sale">
    <div class="video-sale">
           <iframe width="100%" height="400" src="https://www.youtube.com/embed/6-9ey6N-Eig?autoplay=1&loop=1&playlist=GRonxog5mbw" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="banner-sale">
            <img src="<?= $mediaUrl."images/sale/sale-banner.png"; ?>" alt="">
    </div>
    <ol class="products list items product-items">
    <?php  foreach ($saleCate as $product){ $url = $product->getProductUrl(); ?>
        <li class="item product product-item">                
            <div class="product-item-info" data-container="product-grid">
            <a href="http://te.com/demo-1.html" class="product photo product-item-photo" tabindex="-1">

            <span class="product-image-container" style="width:240px;">
            <span class="product-image-wrapper" style="padding-bottom: 100%;">
                <img src="<?= $mediaUrl ."catalog/product". $product['image'] ?>" alt="<?= $product->getName()?>">
            </span>
            </span>
            </a>
            <div class="product details product-item-details">
                <strong class="product name product-item-name">
                <a class="product-item-link" href="http://te.com/demo-1.html">
                <?= $product->getName()?>        </a>
                </strong>
                <?php
                        $hasSpecialPrice = false;

                        if ($product->getTypeId() == 'configurable') {
                            $tmpProduct = $product->getTypeInstance()->getUsedProducts($product);
                            foreach($tmpProduct as $item) {
                                if ($item) $tmpProduct = $item;
                                break;
                            }
                        } else $tmpProduct = $product;

                        $singlePrice = $tmpProduct->getPrice();
                        $specialPrice = $tmpProduct->getSpecialPrice();
                        if (!is_null($specialPrice)) $hasSpecialPrice = true;
                        $singlePrice = "$" . number_format($singlePrice, 2);
                        $specialPrice = "$" . number_format($specialPrice, 2);
                        ?>
                <?php if ($hasSpecialPrice) { ?>
                            <span class="price-single">
                                <a href="<?= $url  ?>"><?= $singlePrice ?></a>
                            </span>
                            <span class="special_price">
                                <a href="<?= $url  ?>"><?= $specialPrice ?></a>
                            </span>
                        <?php } else { ?>
                            <span class="single-price">
                                <a href="<?= $url  ?>"><?= $singlePrice ?></a>
                            </span>
                        <?php } ?>

            <div class="product-item-inner hidden">
            <div class="product actions product-item-actions">
            </div>
            </div>
            </div>
            </div>
        </li> 
         <?php } ?>                   
    </ol>
</div>




<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ 
        $(document).ready(function($){
            // check tror link  category
            
            if(($("#cssmenu-left li.parent").hasClass("active"))){
                $("<li class='sub-link'></li>").insertBefore('#cssmenu-left .active .level0');
            } 
            if(($("#cssmenu-left li.parent").hasClass("has-active"))){
                $("<li class='sub-link'></li>").insertBefore('#cssmenu-left .has-active .submenu');
            } 
            // add html + or -
            if(($('#cssmenu-left .level0').hasClass('parent'))){
                $("<a href='javascript:void(0)' title='' class='parent-child'></a>").insertAfter("#cssmenu-left .parent > a");
            }


            // link active
            if($('#cssmenu-left .parent').hasClass('active')){
                $('#cssmenu-left .active > .parent-child').addClass('activeSub');
            }
            if(($("#cssmenu-left li.parent").hasClass("has-active"))){
                $('#cssmenu-left .has-active > .parent-child').addClass('activeSub');
            }
            // code + - 
            $('#cssmenu-left .parent-child').click(function () {
            if($(this).hasClass('activeSub')){
                $(this).removeClass('activeSub');
            }else{
                console.log(this);
                $(this).addClass('activeSub');
            }
            });




            // code filter click
            $('#filter-p').click(function(){
                if($('#layered-filter-block').hasClass('active_filter')){
                    $('#layered-filter-block').removeClass('active_filter');
                    $('.page-products .sidebar-main .filter').removeClass('active_filter');
                } else {
                    $('#layered-filter-block').addClass('active_filter');
                    $('.page-products .sidebar-main .filter').addClass('active_filter');
                }
             });       
        });
    });
</script>