<?php
	
?>
<div class="block block-customer-login">
	<div class="block-title">
		<strong id="block-customer-login-heading" role="heading"
			aria-level="2"><?php /* @escapeNotVerified */ echo $this->getData('cc_title') ?></strong>
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo $this->getData('cc_content') ?></div>
	</div>
	<div class="block-content"
		aria-labelledby="block-customer-login-heading">
		<form class="form form-login"
			action="<?php /* @escapeNotVerified */ echo $this->getFormActionUrl() ?>"
			method="post" id="login-form" data-mage-init='{"validation":{}}'>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login"
				data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
				<div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
				<div class="field email required">
					<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
					<div class="control">
						<input name="login[username]"
							value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
							<?php if ($this->isAutocompleteDisabled()) :?>
							autocomplete="off" <?php endif; ?> id="email" type="email"
							class="input-text"
							title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
							data-validate="{required:true, 'validate-email':true}">
					</div>
				</div>
				<div class="field password required">
					<label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
					<div class="control">
						<input name="login[password]" type="password"
							<?php if ($this->isAutocompleteDisabled()) :?>
							autocomplete="off" <?php endif; ?> class="input-text" id="pass"
							title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
							data-validate="{required:true, 'validate-password':true}">
					</div>
				</div>
				<div class="actions-toolbar">
					<div class="primary">
						<button type="submit" class="action login primary" name="send"
							id="send2">
							<span><?php /* @escapeNotVerified */ echo __('Login') ?></span>
						</button>
					</div>
					<div class="secondary">
						<a class="action remind"
							href="<?php /* @escapeNotVerified */ echo $this->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
</div>