<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
 <?php
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currentStore = $storeManager->getStore();
    $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<meta property="og:image" content="/pub/media/logo/stores/1/logo-home-icon.png">
<span data-action="toggle-nav" class="action nav-toggle 1">
<span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span>
	<img src="<?= $mediaUrl."images/mobile/icon-menu.png"; ?>" class=""/>
</span>
<?php if ($block->isHomePage()):?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<?php endif ?>
        <img style="display: inline-block; width: auto; height: 66px; margin-right: 20px;" src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-30496170-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-30496170-1');
</script>
<!-- End Global site tag -->

<!-- Facebook Pixel Code -->

<script>

    !function(f,b,e,v,n,t,s)

    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?

    n.callMethod.apply(n,arguments):n.queue.push(arguments)};

    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';

    n.queue=[];t=b.createElement(e);t.async=!0;

    t.src=v;s=b.getElementsByTagName(e)[0];

    s.parentNode.insertBefore(t,s)}(window,document,'script',

    'https://connect.facebook.net/en_US/fbevents.js');

    fbq('init', '987335338072690'); 

    fbq('track', 'PageView');

    </script>

    <noscript>

    <img height="1" width="1"

    src="https://www.facebook.com/tr?id=987335338072690&ev=PageView

    &noscript=1"/>

</noscript>

<!-- End Facebook Pixel Code -->

<style>
    @media only screen and (max-width: 767px) {
        .post-view .post-content .post-text-hld iframe {
            height: 50vw !important;
        }
    }
</style>