<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>


<div class="block block-search" id="topSearchWrap_mb">
    <!-- <div class="block block-title"><strong>Search</strong></div> -->
    <div id="clickTopSearchIcon_mb"></div>

    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <!-- <label class="label" for="search" data-role="minisearch-label"><span>Search</span></label>-->
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?= $helper->getQueryParamName() ?>"
                           value="<?= $helper->getEscapedQueryText() ?>"
                           placeholder="<?= __('What are looking for?'); ?>"
                           class="input-text"
                           maxlength="<?= $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?= __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){ 
        $(document).ready(function($) {
            $('#topSearchWrap_mb #clickTopSearchIcon_mb').click(function(){
                if ($("#topSearchWrap_mb > .block-content").hasClass("active")){

                    $('#topSearchWrap_mb > .block-content').removeClass('active');
                    $('#topSearchWrap_mb > .block-content').css('display', 'none');
                } else{
                    $('#topSearchWrap_mb > .block-content').addClass('active');
                    $('#topSearchWrap_mb > .block-content').css('display', 'block');
                }
                
            });
        }); 
    });
</script>