<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>
<div id="contaier-fild">
	<div class="row header-top">
		<div class="promotion col-md-6 col-sm-6">
			
			<span><a href="https://www.youtube.com/embed/E2_w26_jf0o" style="color: #fff;">NAMI SONIC VIBRATION MACHINE</a></span>
			
		</div>
		<div class="social-right col-md-6 col-sm-6">  
			<div class="box-new-promotion-post">
				<li id="new-promotion-post"><a href="<?= $baseUrl ?>#promotion-product" title="" >NEWS & PROMOTIONS</a>
                </li>
			</div>
			
			<span class="lane-top-social">|</span>
			<span><a href="<?= $baseUrl  ?>socialMediaGallery" title="">social media gallery</a></span>
		</div>
	</div>	
</div>