<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
$context = $ObjectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
$customer_group_current = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_GROUP);
$helper = $this->helper("Lof\HidePrice\Helper\Data");
$validator = $ObjectManager->get('Lof\HidePrice\Model\Validator');
$maxWidth = $helper->getConfig('general/max_width');
$maxHeight = $helper->getConfig('general/max_height');
$minWidth = $helper->getConfig('general/min_width');
$minHeight = $helper->getConfig('general/min_height');
$connection = $helper->_resource->getConnection();
$table = $helper->_resource->getTableName('lof_hideprice_product');

$storeManager = $ObjectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
                $where = ' entity_id = '.$_product->getId();
                $select = 'SELECT * FROM ' . $table.' WHERE'.$where;
                $hideprice = $connection->fetchAll($select);
                $validate = $validator->validate($_product->getId());
                            ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?php   
                        $buy_one_get_one = '';
                        if($_product->getResource()->getAttribute('buy_one_get_one_free')){
                            $buy_one_get_one = $_product->getResource()->getAttribute('buy_one_get_one_free')->getFrontend()->getValue($_product);
                    }?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php if ($buy_one_get_one == 'Yes') {?>
                            <img alt="buy one get one free" class="buy_get_one_list" src="<?= $baseUrl ?>/pub/media/wysiwyg/IMG_BUY_FREE/buy-one-get-one-free.png">
                        <?php } ?>
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details item-information">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php // echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php // echo $block->getProductDetailsHtml($_product); ?>
                        <?php $show_price = $_product->getIn_store_only_price();

                        if(!is_null($show_price)){
                        if (count($hideprice) > 0 || $validate) {
                                            if(count($hideprice) > 0) { ?>
                        <!-- <div class="price-box price-final_price">
                            <span class="price-container price-final_price tax weee">
                                <span id="product-price-128" class="price-wrapper ">
                                <span class="price">$<?=  $show_price ?>.00</span>    </span>
                                </span>

                        </div> -->
                        <?php  }}} ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): 
                                        if (count($hideprice) > 0 || $validate) {
                                        if(count($hideprice) > 0) {
                                            $hideprice = $helper->hideprice->getCollection()->addFieldToFilter('hideprice_id',$hideprice[0]['hideprice_id']);
                                        }elseif($validate) {
                                            $hideprice = $helper->hideprice->getCollection()->addFieldToFilter('hideprice_id',$validate);
                                        }
                                        foreach ($hideprice as $key => $_hideprice) {
                                            $customer_group = json_decode($_hideprice->getCallforpriceCustomergroup(),true);
                                            $store_id = json_decode($_hideprice->getStoreId(),true);
                                            
                                            if($_hideprice->getIsActive() == 1 && (in_array($customer_group_current,$customer_group) == true  || ((in_array(0,$customer_group) ==false && $isLoggedIn ==false) || in_array(0,$customer_group) ==true)) && (in_array($helper->getStoreId(), $store_id) || in_array(0,$store_id ))) {
                                                echo "<p class='callforprice_text'><a href='#' class='btnfancy_".$_product->getId()." action primary'>".$helper->filter($_hideprice->getCallforpriceText())."</a></p>";
                                                echo "<div id='hideprice_content_".$_product->getId()."' style='display: none;'>".$helper->filter($_hideprice->getContent())."</div>";
                                                ?>
                                                 <script type="text/javascript">
                                                    require([
                                                        'jquery',
                                                        'Lof_All/lib/fancybox/jquery.fancybox.pack'
                                                        ], function($){
                                                        jQuery(document).ready(function($) {
                                                            $('.formbuilder-form').prev().remove();
                                                            <?php if(!empty($helper->filter($_hideprice->getContent()))) { ?>
                                                            jQuery(".btnfancy_<?php echo $_product->getId(); ?>").fancybox({
                                                                'href'   : '#hideprice_content_<?php echo $_product->getId(); ?>',
                                                                'titleShow'  : false,
                                                                'transitionIn'  : 'elastic',
                                                                'transitionOut' : 'elastic',
                                                                <?php if((int)$minWidth > 0) { echo "'minWidth' : ".$minWidth .","; } ?>
                                                                <?php if((int)$minHeight > 0) { echo "'minHeight' : ".$minHeight .","; } ?>
                                                                <?php if((int)$maxWidth > 0) { echo "'maxWidth' : ".$maxWidth .","; } ?>
                                                                <?php if((int)$maxHeight > 0) { echo "'maxHeight' : ".$maxHeight .","; } ?>
                                                            });
                                                            <?php } ?>
                                                            $('#hideprice_content_<?php echo $_product->getId(); ?>').find('#entity_id').val('<?php echo $_product->getId(); ?>');
                                                            $('#hideprice_content_<?php echo $_product->getId(); ?>').find('#hideprice_id').val('<?php echo $_hideprice->getHidepriceId(); ?>');
                                                        });

                                                    });
                                                </script>
                                                <?php
                                            }
                                        }
                                    } ?>
                                <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
