<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Included Items');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = true;
        }
    break;
    
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = true;
        }
    break;


    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = true;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>

<!-- code bundle  <=> upsell -->
    <?php if ($type == 'upsell'): ?>
    
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php endif; ?>
    <?php if ($type == 'upsell'): ?>
        <div class="block-title title" id="title-related">
            <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?>: (<?= count($items); ?>)</strong>
        </div>
    <?php endif; ?>
    <?php if ($type == 'upsell'): ?>
    <div id="related-items-bundle" class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <div class="products list items product-items" id="item-related-product">
            <div class="row">
                <?php $iterator = 1; 
                $sum = 0;
                ?>

                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'upsell'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="col-md-12 col-sm-6 col-xs-6 item-related">' : '</div><div class="col-md-12 col-sm-6 col-xs-6 item-related">' ?>
                
                <div class=" <?php /* @escapeNotVerified */ echo $available; ?>">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <div class="col-md-2 box-related">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                    </a>
                    </div>
                    <div class="col-md-8 box-text-item">
                         <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?><?php  $lampk = $block->escapeHtml($_item->getPrice()); $sum += $lampk; ?></a>
                        </strong>
                         <span class="text-include-price">
                                <?php echo count($_item); ?> Included in Price
                        </span>
                        <span class="text-short-description">
                                <?php echo $_item->getShortDescription(); ?>
                        </span>
                    </div>
                    
                    <div class="col-md-2 product details product-item-details">
                     

                        <?php // /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                        <div class="price-final_price">
                        <?php $specialPrice = $_item->getSpecialPrice(); 
                        if(!is_null($specialPrice)){?>
                            <span class="price"><?= "$".number_format($block->escapeHtml($_item->getPrice()), 2);?></span>
                            <span class="price"><?= "$".number_format($block->escapeHtml($_item->getSpecialPrice()), 2);?></span>
                            <?php } else{ ?>
                            <span class="price"><?= "$".number_format($block->escapeHtml($_item->getPrice()), 2);?></span>
                            <?php } ?>
                        </div>
                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions product-item-cart">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endif; ?>
                    <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                <?php endforeach ?>
                <?php if ($type == 'upsell'): ?>
                <div class="col-md-12 col-sm-12 col-xs-12 item-related">
                        <div class="col-md-9">
                        <?php

                            // get current product name & ID & Price
                            $objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
                            $product        = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
                             
                            $id       = $product->getId();
                            $title  = $product->getName();
                            $priceS =  $product->getSpecialPrice();
                             if(!is_null($priceS)){
                                $countPriceB =  $sum *($priceS/100);
                             }
                        // $product1 = $objectManager->get('Magento\Catalog\Model\Product')->load($id);
                        // $bundleObj=$product1->getPriceInfo()->getPrice('final_price');
                        // $basePrice = $product1->getFinalPrice();
                          
                        ?>
                        </div>
                        <div class="col-md-3">
                            <p class="count-price-bundle">Total Price: <span class="price">
                            <?php if(!is_null($priceS)){
                                echo "$".number_format("$countPriceB",2,",","."); 
                                } else{
                                    echo "$".number_format("$sum",2,",","."); 
                                }
                                ?></span></p>
                            <span class="count-text-bundle">Total number of items:<?= count($items); ?></span>
                            <div class="product actions product-item-actions product-item-cart">
                                <div class="actions-primary">
                                    <button class="action tocart primary" id="primary-button-bundle" type="button" title="Add to Cart">
                                    <span>Add to Cart</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                </div>
                <?php endif; ?>
                <script type="text/javascript">
                    require([ 'jquery', 'jquery/ui'], function($){ 
                        $(document).ready(function($){
                            // click cart
                            $("#primary-button-bundle").click(function(){
                                $("#product-addtocart-button").trigger("click");
                            });
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
<?php endif;?>

<!-- #code bundle  <=> upsell -->

<!-- code related -->
<?php if (isset($items) && ($type == 'related')) { ?>
    <div class="sliderDPWrapper <?= $type ?>">
        <div class="block-title title" id="title-related">
            <strong id="block-upsell-heading" role="heading" aria-level="2"><?= $title ?></strong>
        </div>
        <div class="clearfix pad20"></div>
        <div id="<?= $type ?>Slider" class="carousel slide" data-ride="carousel" data-interval="false">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php $i = 1; ?>
                <?php foreach($items as $_item) { ?>
                    <?php if ($i % 4 == 1) { ?>
                    <div class="item <?= ($i == 1)?' active':'' ?>">
                        <div class="row">
                    <?php } ?>

                    <div class="col-xs-6 col-sm-3">
                        <div class="innerSliderDP">
                            <a href="<?= $block->getProductUrl($_item) ?>">
                                <?php
                                $imgUrl = $block->getImage($_item, 'category_page_list')->getImageUrl();
                                // $mediaUrl .'catalog/product'. $_item->getThumbnail()
                                ?>
                                <img src="<?= $imgUrl  ?>" />
                                <p><?= $_item->getName() ?></p>
                                <!-- $block->getProductPrice($_item) ?> -->
                            </a>
                        </div>
                    </div>

                    <?php if ($i % 4 == 0 || $i == count($items)) { ?>
                        </div>
                    </div>
                    <?php } ?>
                    <?php $i++; ?>
                <?php } ?>
            </div>

            <!-- Controls -->
            <a href="#<?= $type ?>Slider" role="button" data-slide="prev">
                <div class="prevButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
            </a>
            <a href="#<?= $type ?>Slider" role="button" data-slide="next">
                <div class="nextButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
            </a>
        </div>
    </div>
<?php } ?>
<!--# code related -->

<!-- hoalexim code crosssell -->
<?php if (isset($items) && ($type == 'crosssell')) { ?>
    <div class="sliderDPWrapper page-products <?= $type ?>" style="margin-top: 50px; margin-bottom: 50px; clear: both;">
        <div class="block-title title" id="title-crosssell" style="margin: 0px 10px 20px;">
            <strong id="block-upsell-heading" role="heading" aria-level="2"><?= $title ?></strong>
        </div>
        <div class="clearfix pad20"></div>
        <div id="<?= $type ?>Slider" class="carousel slide" data-ride="carousel" data-interval="false">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php $i = 1; ?>
                <?php foreach($items as $_item) { ?>
                    <?php if ($i % 4 == 1) { ?>
                    <div class="item <?= ($i == 1)?' active':'' ?>">
                        <div class="row">
                    <?php } ?>

                    <div class="col-xs-6 col-sm-3" style="text-align: center;">
                        <div class="innerSliderDP product-item product-item-details">
                            <a href="<?= $block->getProductUrl($_item) ?>">
                                <?php
                                $imgUrl = $block->getImage($_item, 'category_page_list')->getImageUrl();
                                // $mediaUrl .'catalog/product'. $_item->getThumbnail()
                                ?>
                                <img src="<?= $imgUrl  ?>" />
                                <div class="product-item-name">
                                    <a style="width: 100%; text-align:  center;">
                                        <p style="overflow: hidden; height: 47px; line-height: 16px; text-overflow: ellipsis; margin-top: 10px;"><?= $_item->getName() ?></p>
                                    </a>
                                </div>
                                <!-- $block->getProductPrice($_item) ?> -->
                            </a>
                        
                            <div class="product details">
                         
                            <?php // /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <div class="price-box" style="min-height: 50px;">
                            <?php $specialPrice = $_item->getSpecialPrice(); 
                            if(!is_null($specialPrice)){?>
                                <div class="special-price"><span class="price"><?= "$".number_format($block->escapeHtml($_item->getSpecialPrice()), 2);?></span></div>
                                <div class="old-price" style="margin-top: 10px;"><span class="price"><?= "$".number_format($block->escapeHtml($_item->getPrice()), 2);?></span></div>
                                <?php } else{ ?>
                                <div class="special-price"><span class="price"><?= "$".number_format($block->escapeHtml($_item->getPrice()), 2);?></span></div>
                                <?php } ?>
                            </div>
                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions product-item-cart">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary" style="display: inline-block;">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                    </div>

                    <?php if ($i % 4 == 0 || $i == count($items)) { ?>
                        </div>
                    </div>
                    <?php } ?>
                    <?php $i++; ?>
                <?php } ?>
            </div>

            <!-- Controls -->
            <!-- <a href="#<?= $type ?>Slider" role="button" data-slide="prev">
                <div class="prevButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
            </a>
            <a href="#<?= $type ?>Slider" role="button" data-slide="next">
                <div class="nextButtonWrap btHomeSlider" aria-hidden="true"><span></span></div>
            </a> -->
        </div>
    </div>
<?php } ?>
<!--# code crosssell -->
<?php endif;?>