<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="col-md-4 box-ads">
    <div class="box-ads1">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
        <?php } ?>
        <div class="box-text">
            <p class="title-ads"><a href="<?php echo $_postUrl ?>" title=""><?php echo $_postName; ?></a></p>
            <?php echo $this->getInfoHtml() ?>
            <div class="box-read-more">
                <a href="<?php echo $_postUrl ?>" title="" class="read-more-ads">Read More</a>                
            </div>
        </div>
    </div>
</div>
